---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/anhdong/duckora

name: duckora
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-silverblue
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - vscodium.repo
      copr:
        - atim/starship
      cleanup: true
    install:
      packages:
        - codium
        - starship
    remove:
      packages:
        - gnome-software
        - firefox
        - firefox-langpacks
        - htop
        - nvtop

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        install:
          - io.github.kolunmi.Bazaar
          - org.gnome.Loupe
          - com.vixalien.sticky
          - org.localsend.localsend_app
          - app.zen_browser.zen
          - com.notesnook.Notesnook
          - dev.vencord.Vesktop
          - io.github.Faugus.faugus-launcher
          - io.ente.auth
          - com.bitwarden.desktop
          - org.kde.kdenlive
          - org.inkscape.Inkscape
          - com.obsproject.Studio

  - type: gnome-extensions
    install:
      - Blur my Shell
      - Dash2Dock Animated
      - Just Perfection
      - Logo Menu
      - Clipboard History
      - Color Picker
      - GNOME Fuzzy App Search
      - GSConnect
      - Vitals
      # Search light (unavailble in 44 yet)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
